include SDL/Android.mk
include SDL2_image/external/libwebp-0.3.0/Android.mk
include SDL2_image/Android.mk
include SDL2_mixer/external/libmikmod-3.1.12/Android.mk
include SDL2_mixer/external/smpeg2-2.0.0/Android.mk
include SDL2_mixer/Android.mk
include SDL2_net/Android.mk
include SDL2_ttf/Android.mk
include src/Android.mk
include utils/Android.mk
