Ubuntu:

apt-get install build-essential m4 bison flex autoconf automake pkg-config intltool gawk zlib1g-dev libc6-i386 zip python subversion git chrpath wget

sudo apt-get install software-properties-common
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java6-installer
